import type { Metadata } from "next";
import { Syne } from "next/font/google";
import "./globals.css";

const mukta = Syne({
  variable: "--font-geist-sans",
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Your CR",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

import { Toaster } from "sonner";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta name="google-adsense-account" content="ca-pub-1132020137464868" />
      </head>
      <body className={`${mukta.className}`} suppressHydrationWarning>
        {children}
        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
